campaign: add get all endpoint
arrecadar/api-express pull request #12
Opened 2018-04-24 00:34 UTC by uselessdev

Add campaign resources

``` http
GET /campaigns
```

2018-04-29 16:57 UTC, flyingluscas commented on CHANGELOG.md
> +  - [x] GET /campaigns
isso deveria estar no primeiro commit não?

2018-04-29 16:58 UTC, flyingluscas commented on app/Campaigns/repository.js
> +const create = campaign => new Campaign(campaign).save().catch(handleSaveErrors)
@uselessdev o que você acha de quebrar essa linha?

2018-04-29 17:00 UTC, flyingluscas commented on app/Campaigns/request.js
> +  ong: 'string|required'
@uselessdev esse one seria o ID dela? nesse caso não seria mais explicito colocar `ong_id`?

2018-04-29 17:01 UTC, flyingluscas commented on app/Campaigns/repository.js
> +const findOne = (id, query) => (
@uselessdev o arg `query` nao é usado, precisa dele?

2018-04-29 17:02 UTC, flyingluscas commented on app/Campaigns/repository.js
> +    .findById({ _id: id })
essa alteração deveria estar no primeiro commit **campaign: add get one endpoint**, estão duplicados

2018-04-29 17:03 UTC, flyingluscas requested changes
@uselessdev comentei alguns pontos ;)

2018-04-29 18:25 UTC, uselessdev commented on app/Campaigns/request.js
> +  ong: 'string|required'
não tenho certeza, porque isso passa pelo `.populate` e acaba recebendo um objeto de `Ong`, o que você acha?

2018-04-29 19:19 UTC, hiwllc commented on CHANGELOG.md
> +  - [x] GET /campaigns
done

2018-04-29 23:54 UTC, flyingluscas commented on app/Campaigns/request.js
> +  ong: 'string|required'
@uselessdev acho valido, se você concorda que `ong_id` faz sentido na interface da API

2018-05-01 21:56 UTC, flyingluscas approved these changes

2018-05-01 23:25 UTC, merged