authenticate: add auth flow
arrecadar/api-express pull request #22
Opened 2018-05-03 01:12 UTC by uselessdev

2018-05-09 13:59 UTC, guuibayer commented on bootstrap/authenticate.js
> +    secret: 'secret',
Só por curiosidade, aqui vai o secret token?

2018-05-09 14:49 UTC, uselessdev commented on bootstrap/authenticate.js
> +    secret: 'secret',
Não, ai vai o secret da session, como estamos em desenvolvimento ainda, deixei em texto plano, eventualmente vamos pensar em uma forma melhor de lidar com `secrets`.

2018-05-09 14:50 UTC, uselessdev commented on bootstrap/authenticate.js
> +    secret: 'secret',
Eu tenho que pushar umas coisas novas.

2018-05-12 00:31 UTC, flyingluscas commented
@uselessdev esse PR está pronto pra review?

2018-05-12 19:50 UTC, uselessdev commented
ainda não @flyingluscas

2018-05-12 21:03 UTC, uselessdev commented
agora está @flyingluscas

2018-05-13 04:50 UTC, flyingluscas requested changes

2018-05-13 04:50 UTC, flyingluscas commented on config/app.js
> +  key: process.env.APP_KEY || 'secret',
@uselessdev vc não acha que APP_KEY e key são muito genéricos? nao seria melhor deixar mais especifico?

2018-05-13 04:58 UTC, uselessdev commented on config/app.js
> +  key: process.env.APP_KEY || 'secret',
Não sei como deixar isso mais específico, porque ele ta indo tanto `session` quanto pra `jwt` ai tava até pensando em separar essas coisas.

2018-05-13 05:01 UTC, flyingluscas commented on config/app.js
> +  key: process.env.APP_KEY || 'secret',
@uselessdev acho justo separar, nao me parece bom isso ser duas coisas, faz sentido?

2018-05-13 05:02 UTC, uselessdev commented on config/app.js
> +  key: process.env.APP_KEY || 'secret',
faz sentido sim

2018-05-14 03:56 UTC, flyingluscas submitted a review, later dismissed

2018-05-14 04:01 UTC, merged