routes: update public routes
arrecadar/api-express pull request #37
Opened 2018-05-26 15:13 UTC by uselessdev

The routes below are now public routes:

- GET /ongs
- GET /ongs/:id
- GET /campaigns
- GET /campaigns/:id
- POST /users

2018-05-26 15:24 UTC, flyingluscas requested changes

2018-05-26 15:24 UTC, flyingluscas commented on app/Users/routes.js
> +// Router.get('/', users.index)
@uselessdev isso precisa ficar comentado?

2018-05-26 15:25 UTC, hiwllc commented on app/Users/routes.js
> +// Router.get('/', users.index)
Isso pode ser removido, só deixei comentado porque não sabia se ia utilizar isso ainda

2018-06-03 02:53 UTC, flyingluscas approved these changes

2018-06-03 02:56 UTC, merged