auth: refactor auth flow
arrecadar/api-express pull request #38
Opened 2018-05-26 15:58 UTC by uselessdev

Atualmente o fluxo de autorização é feito em um pacote externo
isso fica ruim porque acabamos ficando presos em pacote pra iss.

Este PR traz essa responsabilidade para o core da API.

2018-05-26 16:15 UTC, flyingluscas requested changes

2018-05-26 16:15 UTC, flyingluscas commented on app/Auth/controller.js
> +const logout = (request, response) => {
@uselessdev pq precisamos de uma rota de logout na API?

2018-05-26 16:15 UTC, flyingluscas commented on app/Auth/middleware.js
> +      'Unauthorized'
@uselessdev vi que no arquivo `app/Auth/controller.js` vc responde 401 mas com a mensagem `invalid credentials`, nao seria melhor manter um padrão entre essas mensagens?

2018-05-26 16:15 UTC, flyingluscas commented on bootstrap/strategies/jwt.js
> +  fromUrlQueryParameter('token'),
@uselessdev nao sei se é uma boa ideia receber o token de várias formas (header, body e query string), acho que via header é a forma mais segura, e deveria ser a única, faz sentido?

2018-05-26 16:20 UTC, uselessdev commented on bootstrap/strategies/jwt.js
> +  fromUrlQueryParameter('token'),
Acho que faz, mas qual formato no header? `withScheme` ou `AsBearerToken`?

2018-05-26 16:21 UTC, hiwllc commented on app/Auth/middleware.js
> +      'Unauthorized'
Aqui, a gente só verifica se o usuário está logado, como não é uma tentativa de login eu coloquei `Unathorized` mas podemos deixar tudo como `invalid`

2018-05-26 16:22 UTC, hiwllc commented on app/Auth/controller.js
> +const logout = (request, response) => {
não precisamos, vou remover

2018-05-26 16:22 UTC, flyingluscas commented on bootstrap/strategies/jwt.js
> +  fromUrlQueryParameter('token'),
AsBearerToken parece bom

2018-05-29 14:10 UTC, iamgbayer requested changes

2018-05-29 14:10 UTC, guuibayer commented on app/Routes.js
> +const Auth = require('./Auth')
Poderia explicitar o nome `Authentication`, o que acha?

2018-05-29 21:35 UTC, uselessdev commented on app/Routes.js
> +const Auth = require('./Auth')
Acho que concordo, vou fazer isso, valeu @guuibayer

2018-05-31 00:41 UTC, flyingluscas commented on app/Auth/controller.js
> +      return handleUnauthorized(response)
:heart:

2018-05-31 00:57 UTC, flyingluscas requested changes

2018-05-31 00:57 UTC, flyingluscas commented on app/Auth/middleware.js
> +  if (request.isAuthenticated()) {
@uselessdev da pra fazer um destructuring aqui nao? example:

``` js
const authorize = ({ isAuthenticated }, response, next) => {
  if (isAuthenticated()) {
    ...
```

2018-05-31 00:57 UTC, flyingluscas commented on bootstrap/strategies/jwt.js
> +  fromHeader
@uselessdev nao tem necessidade de quebrar a linha aqui, dado que é somente uma prop, faz sentido?

2018-05-31 00:57 UTC, flyingluscas commented on bootstrap/strategies/jwt.js
> +  User
@uselessdev isso ta meio confuso, nao seria melhor colocar os dois argumentos e vars e depois passar elas aqui?

2018-05-31 00:57 UTC, flyingluscas commented on bootstrap/strategies/local.js
> +  token: jwt.sign({ user: user.id }, key, {
@uselessdev aqui nao seria criar uma `const token = ...` e passar ela aqui?

2018-05-31 00:57 UTC, flyingluscas commented on bootstrap/strategies/local.js
> +      throw new Error('invalid credentials')
@uselessdev pq a mensagem está em lowercase?

2018-06-03 02:16 UTC, flyingluscas approved these changes

2018-06-03 02:23 UTC, merged